import "./globals.css";
import { Nunito } from "next/font/google";
import Link from "next/link";
import Header from "./Header";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "NxI3-crud",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <title>NxI3-crud</title>
      <body className={nunito.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
